apiVersion: apps/v1
kind: Deployment

metadata:
  name: simple-node-deployment

spec:
  replicas: 2

  selector:
    matchLabels:
      app: simple-node-app

  template:
    metadata:
      labels:
        app: simple-node-app

    spec:
      containers:
        - name: simple-node-container
          image: starrajendran/simple-node-app:v1

          ports:
            - containerPort: 3000